### ISSUE TITLE
Error when installing libp2p-mplex 0.8.5 on Windows 10

### ISSUE THREAD

**Issue by emclab** [libp2p/libp2p#87]
After `npm install` `ipfs` and `libp2p` with `nodejs 12.14.1`,  the installation of `libp2p-mplex` has an error:
 
$npm install libp2p-mplex                                                                         
> gc-stats@1.4.0 install C:\d\code\js\libp2p_pnet\node_modules\ipfs\node_modules\gc-stats
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://node-binaries.s3.amazonaws.com/gcstats/v1.4.0/Release/node-v72-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for gc-stats@1.4.0 and node@12.14.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framew
ork 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it i
s installed elsewhere.  [C:\d\code\js\libp2p_pnet\node_modules\ipfs\node_modules\gc-stats\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\JunC\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\JunC\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\d\\code\\js\\libp2p_pnet\\node_modules\\ipfs\\node_modules\\gc-stats\\build\\gcstats\\v1.4.0\\Release\\node-v72-win32-x64\\gcstats.node" "--module_name=gcstats" "--module_path=C:\\d\\code\\js\\libp2p_pnet\\node_modules\\ipfs\\node_modules\\gc-stats\\build\\gcstats\\v1.4.0\\Release\\node-v72-win32-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd C:\d\code\js\libp2p_pnet\node_modules\ipfs\node_modules\gc-stats
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\JunC\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\d\code\js\libp2p_pnet\node_modules\ipfs\node_modules\gc-stats\build\gcstats\v1.4.0\Release\node-v72-win32-x64\gcstats.node --module_name=gcstats --module_path=C:\d\code\js\libp2p_pnet\node_modules\ipfs\node_modules\gc-stats\build\gcstats\v1.4.0\Release\node-v72-win32-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\D\code\js\libp2p_pnet\node_modules\ipfs\node_modules\gc-stats\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Windows_NT 10.0.18362
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\D\\code\\js\\libp2p_pnet\\node_modules\\ipfs\\node_modules\\gc-stats\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\d\code\js\libp2p_pnet\node_modules\ipfs\node_modules\gc-stats
node-pre-gyp ERR! node -v v12.14.1
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\JunC\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\d\code\js\libp2p_pnet\node_modules\ipfs\node_modules\gc-stats\build\gcstats\v1.4.0\Release\node-v72-win32-x64\gcstats.node --module_name=gcstats --module_path=C:\d\code\js\libp2p_pnet\node_modules\ipfs\node_modules\gc-stats\build\gcstats\v1.4.0\Release\node-v72-win32-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN karma-edge-launcher@0.4.2 requires a peer of karma@>=0.9 but none is installed. You must install peer dependencies yourself.
npm WARN karma-junit-reporter@1.2.0 requires a peer of karma@>=0.9 but none is installed. You must install peer dependencies yourself.
npm WARN karma-mocha-reporter@2.2.5 requires a peer of karma@>=0.13 but none is installed. You must install peer dependencies yourself.
npm WARN pnet-ipfs-example@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\ipfs\node_modules\aegir\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\ipfs\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gc-stats@1.4.0 (node_modules\ipfs\node_modules\gc-stats):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gc-stats@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ libp2p-mplex@0.8.5
updated 1 package and audited 19205 packages in 32.795s
found 0 vulnerabilities

**Comment by emclab** [comment]
Here is the part of `package.json` file:

"dependencies": {
    "ipfs": "^0.40.0",
    "libp2p": "^0.26.2",
    "libp2p-mplex": "^0.8.5"
  }
